@startuml

package "org.quickfixj:quickfixj-base"  as base {
component quickfixj_base
}

package "org.quickfixj:quickfixj-messages-all"  as all {
package field
package fixlatest
package fixt11
package fix50sp2
package fix50sp1
package fix50
package fix44
package fix43
package fix42
package fix41
package fix40
}

package "org.quickfixj:quickfixj-orchestration"  as orc {
component quickfixj_orchestration
}

package "io.fixprotocol.orchestrations:fix-standard"  as ftc {
component fix_standard_orchestration
}

quickfixj_orchestration  .up.> fix_standard_orchestration  : derived from
orc .up.> ftc  : build depends
all .left.> prune : build depends
all -up-> base : depends

package "org.quickfixj:class-pruner-maven-plugin"  as prune {
component class_pruner_maven_plugin
}

package "org.quickfixj:quickfixj-codegenerator"  as codegen {
component quickfixj_codegenerator
}

package "org.quickfixj:quickfixj-orchestra"  as r2q {
component quickfixj_from_fix_orchestra_code_generator_maven_plugin
component quickfixj_from_fix_orchestra_dictionary_generator_maven_plugin
}

fixlatest ..> r2q : build depends
fixlatest .left.> orc : build depends

all .up.> codegen  : build depends

package "org.quickfixj:quickfixj-messages-fixlatest" as fix_latest {
package fixlatest_subset_of_field
package duplicate_of_fixlatest
}

package "org.quickfixj:quickfixj-messages-fixt11"  as  fix_t11 {
package fixt11_subset_of_field
package duplicate_of_fixt11t
}

note bottom of fix_latest
example: alternative way of publishing packages
package names are the same as in quickfixj-messages-all, the classes are copied to these artefacts
end note


fix_latest -up-> fix_t11  : runtime depends
fix_latest -up-> base : depends
fix_t11 -up-> base : depends

@enduml