name: Java CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [reopened, opened, synchronize]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-14]
        java: [8, 11, 21]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Test with Maven
        run: mvn install -B -V -D"maven.javadoc.skip"="true"
