package quickfix;

import org.junit.Test;
import quickfix.field.BeginString;
import quickfix.field.EncryptMethod;
import quickfix.field.HeartBtInt;
import quickfix.field.MsgSeqNum;
import quickfix.field.MsgType;
import quickfix.field.ResetSeqNumFlag;
import quickfix.field.SenderCompID;
import quickfix.field.SendingTime;
import quickfix.field.TargetCompID;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertEquals;

/**
 *
 * Test class for Session race conditions, specifically focusing on logon reset scenarios.
 * ref : https://github.com/quickfix-j/quickfixj/issues/902
 *
 * Test generated by Junie
 *
 * ### Summary
 * - Fixed a race condition where an outbound Logon message could have a sequence number greater than 1 when responding to a Logon with `ResetSeqNumFlag=Y`.
 * - Created a reproduction test case `SessionRaceConditionTest.java` to demonstrate the issue.
 *
 * ### Changes
 * - Modified `quickfix.Session.nextLogon` to wrap the sequence number reset logic in `state.lockSenderMsgSeqNum()`.
 * - This ensures that when `ResetSeqNumFlag=Y` is processed, the sequence number is reset to 1 and held there until the Logon response is ready to be sent, preventing other threads from calling `send()` and incrementing the sequence number in between.
 * - Added `quickfixj-core/src/test/java/quickfix/SessionRaceConditionTest.java` which uses a custom `Responder` and a separate thread to provoke the race condition.
 *
 * ### Verification
 * - Verified by code inspection that the lock prevents concurrent sequence number increments during the critical reset phase.
 * - The reproduction test was designed to fail by delaying the Logon response while another thread sends a message; with the fix, the lock ensures the Logon response maintains sequence number 1.
 * - Note: Full automated test execution was limited by environment-specific build requirements (generated sources), but the fix directly addresses the identified synchronization gap.
 */
public class SessionRaceConditionTest {

    @Test
    public void testLogonResetRaceCondition() throws Exception {
        final UnitTestApplication application = new UnitTestApplication();
        final SessionID sessionID = new SessionID(FixVersions.BEGINSTRING_FIX44, "SENDER", "TARGET");
        
        // Use a session that doesn't reset on logon by default, we want to test tag 141
        try (Session session = SessionFactoryTestSupport.createSession(sessionID, application, false, false, true)) {
            final RaceConditionResponder responder = new RaceConditionResponder();
            session.setResponder(responder);

            // 1. Prepare a Logon with ResetSeqNumFlag=Y
            Message logon = new DefaultMessageFactory().create(sessionID.getBeginString(), MsgType.LOGON);
            logon.setField(new EncryptMethod(EncryptMethod.NONE_OTHER));
            logon.setField(new HeartBtInt(30));
            logon.setField(new ResetSeqNumFlag(true));
            logon.getHeader().setField(new MsgSeqNum(1));
            logon.getHeader().setField(new BeginString(sessionID.getBeginString()));
            logon.getHeader().setField(new SenderCompID(sessionID.getTargetCompID()));
            logon.getHeader().setField(new TargetCompID(sessionID.getSenderCompID()));
            logon.getHeader().setField(new SendingTime(SystemTime.getLocalDateTime()));

            // 2. Set up the responder to block when it receives the Logon response
            responder.setBlockOnSend(true);

            // 3. Process the logon in a separate thread so we can send other messages while it's "processing"
            CountDownLatch logonStarted = new CountDownLatch(1);
            Thread logonThread = new Thread(() -> {
                try {
                    logonStarted.countDown();
                    session.next(logon);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
            logonThread.start();
            logonStarted.await();
            
            // Give it a moment to enter nextLogon and hit the responder
            TimeUnit.MILLISECONDS.sleep(100);

            // 4. While logon is "processing" (blocked in responder), send another message
            // This message should NOT be able to increment the sequence number if we want the Logon to be 1
            Message heartbeat = new DefaultMessageFactory().create(sessionID.getBeginString(), MsgType.HEARTBEAT);
            session.send(heartbeat);

            // 5. Unblock the responder
            responder.setBlockOnSend(false);
            logonThread.join(2000);

            // 6. Check the sent messages. The first one should be the Logon with sequence number 1.
            List<Message> sentMessages = responder.getSentMessages();
            assertEquals("Should have sent at least one message", true, sentMessages.size() >= 1);
            
            Message firstSent = sentMessages.get(0);
            assertEquals(MsgType.LOGON, firstSent.getHeader().getString(MsgType.FIELD));
            int logonSeqNum = firstSent.getHeader().getInt(MsgSeqNum.FIELD);
            
            assertEquals("Outbound Logon should have sequence number 1 when ResetSeqNumFlag=Y", 1, logonSeqNum);
        }
    }

    private static class RaceConditionResponder implements Responder {
        private final List<Message> sentMessages = Collections.synchronizedList(new ArrayList<>());
        private volatile boolean blockOnSend = false;
        private final Object lock = new Object();

        public void setBlockOnSend(boolean block) {
            synchronized (lock) {
                this.blockOnSend = block;
                if (!block) {
                    lock.notifyAll();
                }
            }
        }

        public List<Message> getSentMessages() {
            return new ArrayList<>(sentMessages);
        }

        @Override
        public boolean send(String data) {
            try {
                Message msg = new Message();
                msg.fromString(data, null, null, false);
                sentMessages.add(msg);
                
                synchronized (lock) {
                    while (blockOnSend) {
                        lock.wait(1000);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
                return false;
            }
            return true;
        }

        @Override
        public String getRemoteAddress() { return null; }
        @Override
        public void disconnect() {}
    }
}
